# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-railties41>=4.1.12:${PORTSDIR}/www/rubygem-railties41 \
	rubygem-turbolinks-rails41>=0:${PORTSDIR}/www/rubygem-turbolinks-rails41

MASTERDIR=	${.CURDIR}/../rubygem-jquery-turbolinks

.include "${MASTERDIR}/Makefile"
