# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	41

RUN_DEPENDS=	rubygem-rails41>=4.1.12:${PORTSDIR}/www/rubygem-rails41

MASTERDIR=	${.CURDIR}/../rubygem-dropzonejs-rails

.include "${MASTERDIR}/Makefile"
