# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX?=	-rails41

RUN_DEPENDS=	rubygem-devise-rails41>=3.2:${PORTSDIR}/devel/rubygem-devise-rails41

MASTERDIR=	${.CURDIR}/../rubygem-devise-async

.include "${MASTERDIR}/Makefile"
