# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-activesupport41>=4.1.12:${PORTSDIR}/devel/rubygem-activesupport41 \
	rubygem-nokogiri>=1.6:${PORTSDIR}/textproc/rubygem-nokogiri \
	rubygem-rails-deprecated_sanitizer-rails41>=1.0.1:${PORTSDIR}/devel/rubygem-rails-deprecated_sanitizer-rails41

MASTERDIR=	${.CURDIR}/../rubygem-rails-dom-testing

.include "${MASTERDIR}/Makefile"
