# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-activesupport41>=4.1.12:${PORTSDIR}/devel/rubygem-activesupport41

MASTERDIR=	${.CURDIR}/../rubygem-enumerize

.include "${MASTERDIR}/Makefile"
