# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-html-pipeline-rails41>=1.11.0:${PORTSDIR}/textproc/rubygem-html-pipeline-rails41

MASTERDIR=	${.CURDIR}/../rubygem-task_list

.include "${MASTERDIR}/Makefile"
