# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

MASTERDIR=	${.CURDIR}/../rubygem-jquery-rails4

.include "${MASTERDIR}/Makefile"

PKGNAMESUFFIX=	41

RUN_DEPENDS=	rubygem-rails-dom-testing-rails41>=1.0:${PORTSDIR}/textproc/rubygem-rails-dom-testing-rails41 \
		rubygem-railties41>=4.1.0:${PORTSDIR}/www/rubygem-railties41 \
		rubygem-thor>=0.14:${PORTSDIR}/devel/rubygem-thor
