# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	41

RUN_DEPENDS=	rubygem-railties41>=4.1.12:${PORTSDIR}/www/rubygem-railties41

MASTERDIR=	${.CURDIR}/../rubygem-jquery-scrollto-rails

.include "${MASTERDIR}/Makefile"
