# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PORTNAME=	jquery-ui-rails
PORTVERSION=	4.2.1

CATEGORIES=	www rubygems
MASTER_SITES=	RG

PKGNAMESUFFIX=	-rails41

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Packaged JavaScript, CSS and image files of jQuery UI for Rails

LICENSE=	MIT

RUN_DEPENDS=	rubygem-railties41>=4.1.12:${PORTSDIR}/www/rubygem-railties41

NO_ARCH=	yes

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
