# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-activemodel41>=4.1.12:${PORTSDIR}/databases/rubygem-activemodel41

MASTERDIR=	${.CURDIR}/../rubygem-rails-observers

.include "${MASTERDIR}/Makefile"
