# Created by: renchap@cocoa-x.com
# $FreeBSD: head/devel/rubygem-systemu/Makefile 357277 2014-06-10 07:39:01Z olgeni $

PORTNAME=	systemu
PORTVERSION=	2.6.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	renchap@cocoa-x.com
COMMENT=	Portable replacement for popen4

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
