# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-activesupport41>=4.1.12:${PORTSDIR}/devel/rubygem-activesupport41 \
	rubygem-nokogiri>=1.4:${PORTSDIR}/textproc/rubygem-nokogiri

MASTERDIR=	${.CURDIR}/../rubygem-html-pipeline

.include "${MASTERDIR}/Makefile"
