# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-activeresource4-rails41>=4.0.0:${PORTSDIR}/www/rubygem-activeresource4-rails41

MASTERDIR=	${.CURDIR}/../rubygem-asana

.include "${MASTERDIR}/Makefile"
