# Created by: renchap@cocoa-x.com
# $FreeBSD$

PORTNAME=      wmi-lite
PORTVERSION=   1.0.0
CATEGORIES=    devel rubygems
MASTER_SITES=  RG

MAINTAINER=    renchap@cocoa-x.com
COMMENT=       A lightweight utility over win32ole for accessing basic WMI

LICENSE=       APACHE20

USE_RUBY=      yes
USE_RUBYGEMS=  yes
RUBYGEM_AUTOPLIST=     yes

.include <bsd.port.mk>
