# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	41

RUN_DEPENDS=	rubygem-redis-actionpack-rails41>=4.0.0:${PORTSDIR}/databases/rubygem-redis-actionpack-rails41 \
	rubygem-redis-activesupport-rails41>=4.1.0:${PORTSDIR}/devel/rubygem-redis-activesupport-rails41 \
	rubygem-redis-store>=1.1.0:${PORTSDIR}/devel/rubygem-redis-store

MASTERDIR=	${.CURDIR}/../rubygem-redis-rails

.include "${MASTERDIR}/Makefile"
