# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-railties41>=4.1.12:${PORTSDIR}/www/rubygem-railties41

MASTERDIR=	${.CURDIR}/../rubygem-d3_rails-rails4

.include "${MASTERDIR}/Makefile"
