# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	3-rails41

RUN_DEPENDS=	rubygem-activerecord41>=4.1.12:${PORTSDIR}/databases/rubygem-activerecord41

MASTERDIR=	${.CURDIR}/../rubygem-acts-as-taggable-on3

.include "${MASTERDIR}/Makefile"
