# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PORTNAME=	responders
PORTVERSION=	1.1.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	1

MAINTAINER=	ports@toco-domains.de
COMMENT=	Simple Ruby DSL for making HTTP requests

LICENSE=	MIT

RUN_DEPENDS=	rubygem-railties41>=4.1.0:${PORTSDIR}/www/rubygem-railties41

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
