# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	4-rails41

RUN_DEPENDS=	rubygem-activemodel41>=4.1.12:${PORTSDIR}/databases/rubygem-activemodel41 \
	rubygem-activesupport41>=4.1.12:${PORTSDIR}/devel/rubygem-activesupport41 \
	rubygem-rails-observers-rails41>=0.1.1:${PORTSDIR}/devel/rubygem-rails-observers-rails41

MASTERDIR=	${.CURDIR}/../rubygem-activeresource4

.include "${MASTERDIR}/Makefile"
