# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-actionpack41>=4.1.12:${PORTSDIR}/www/rubygem-actionpack41 \
	rubygem-activesupport41>=4.1.12:${PORTSDIR}/devel/rubygem-activesupport41

MASTERDIR=	${.CURDIR}/../rubygem-kaminari

.include "${MASTERDIR}/Makefile"
