# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-activerecord41>=4.1.12:${PORTSDIR}/databases/rubygem-activerecord41

MASTERDIR=	${.CURDIR}/../rubygem-default_value_for

.include "${MASTERDIR}/Makefile"
