# Created by: Torsten Zühlsdorff <ports@toco-domains.de>
# $FreeBSD$

PKGNAMESUFFIX=	-rails41

RUN_DEPENDS=	rubygem-railties41>=4.1.12:${PORTSDIR}/www/rubygem-railties41 \
		rubygem-thor>=0.14:${PORTSDIR}/devel/rubygem-thor

MASTERDIR=	${.CURDIR}/../rubygem-jquery-rails

.include "${MASTERDIR}/Makefile"
